meta_product_name: “Miss Helper”

meta_title: “Miss Helper – Choisir votre raquette de padel”

meta_description: “Miss Helper vous aide à comparer des raquettes de padel pour trouver celle qui est faite pour vous. ”

meta_image: “home.png” # should exist in `app/assets/images/`

# twitter_account: “@product_twitter_account” # required for Twitter Cards