meta_product_name: “Miss Helper”

meta_title: “Miss Helper – Tous les bons plans du web”

meta_description: “Miss Helper vous aide à bien acheter pour dénicher de supers offres”

meta_image: "cover.png" # should exist in `app/assets/images/`